import {
  Activity,
  Badge,
  BarChart3,
  Bed,
  BedDouble,
  Bell,
  BookOpen,
  Bookmark,
  Building,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Check,
  CircleX,
  ClipboardList,
  Clock,
  CloudCheck,
  CloudRain,
  CreditCard,
  Database,
  DollarSign,
  Dumbbell,
  Eye,
  Filter,
  Home,
  House,
  IndianRupee,
  Info,
  Layers,
  LayoutList,
  List,
  Lock,
  MonitorCog,
  Pencil,
  PhoneCall,
  Plus,
  Receipt,
  Save,
  ShieldCheck,
  Trash2,
  TrendingUp,
  User,
  UserCheck,
  UserPen,
  UserPlus,
  Users,
  WalletCards,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry: Record<string, LucideIcon> = {
  activity: Activity,
  badge: Badge,
  "bar-chart-3": BarChart3,
  bed: Bed,
  "bed-double": BedDouble,
  bell: Bell,
  "book-open": BookOpen,
  bookmark: Bookmark,
  building: Building,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  check: Check,
  "circle-x": CircleX,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "cloud-check": CloudCheck,
  "cloud-rain": CloudRain,
  "credit-card": CreditCard,
  database: Database,
  "dollar-sign": DollarSign,
  dumbbell: Dumbbell,
  eye: Eye,
  filter: Filter,
  home: Home,
  house: House,
  "indian-rupee": IndianRupee,
  info: Info,
  layers: Layers,
  "layout-list": LayoutList,
  list: List,
  lock: Lock,
  "monitor-cog": MonitorCog,
  pencil: Pencil,
  "phone-call": PhoneCall,
  plus: Plus,
  receipt: Receipt,
  save: Save,
  "shield-check": ShieldCheck,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  user: User,
  "user-check": UserCheck,
  "user-pen": UserPen,
  "user-plus": UserPlus,
  users: Users,
  "wallet-cards": WalletCards,
  wrench: Wrench,
  zap: Zap,
};

export type { LucideIcon };
